baseURL = 'https://opentechschool-zurich.github.io/'
locale = 'en-us'
title = 'OpenTechSchool Zürich'
# theme = 'ananke'
theme = 'congo'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
# disableLanguages = []

enableMissingTranslations = true
enableMissingTranslationPlaceholders = false

[languages]
  [languages.de]
    label = 'Deutsch'
    weight = 3
  [languages.en]
    label = 'English'
    weight = 1

[markup.goldmark.parser.attribute]
    block = true
    title = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
