[[main]]
  name = 'Home'
  pageRef = '_index'
  weight = 10
[[main]]
  name = 'About'
  pageRef = 'about'
  weight = 20
[[main]]
  name = 'Learning'
  pageRef = 'learning'
  weight = 30
[[main]]
  name = 'News'
  pageRef = 'posts'
  weight = 40
[[main]]
  name = 'Contact'
  pageRef = 'contact'
  weight = 50
[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"
